-- 用户认证与权限管理相关表结构
-- 创建时间: 2025-11-24

-- 1. 用户表 (扩展现有USERS表)
-- 如果USERS表不存在则创建
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    REAL_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    AVATAR VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    ROLE_ID BIGINT,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN_TIME TIMESTAMP,
    LAST_LOGIN_IP VARCHAR(50)
);

-- 2. 角色表
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROLE_CODE VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 权限表
CREATE TABLE IF NOT EXISTS PERMISSIONS (
    PERMISSION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    PERMISSION_CODE VARCHAR(100) UNIQUE NOT NULL,
    RESOURCE_TYPE VARCHAR(50) COMMENT '资源类型: menu, button, api',
    RESOURCE_PATH VARCHAR(255) COMMENT '资源路径',
    DESCRIPTION VARCHAR(255),
    PARENT_ID BIGINT,
    SORT_ORDER INTEGER DEFAULT 0,
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 角色权限关联表
CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(PERMISSION_ID),
    UNIQUE (ROLE_ID, PERMISSION_ID)
);

-- 5. 用户会话表 (用于JWT黑名单和会话管理)
CREATE TABLE IF NOT EXISTS USER_SESSIONS (
    SESSION_ID VARCHAR(255) PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(500) NOT NULL,
    REFRESH_TOKEN VARCHAR(500),
    EXPIRES_AT TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(50),
    USER_AGENT VARCHAR(500),
    STATUS INTEGER DEFAULT 1 COMMENT '1:有效 0:已注销',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 6. 操作日志表
CREATE TABLE IF NOT EXISTS OPERATION_LOGS (
    LOG_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT,
    USER_NAME VARCHAR(50),
    OPERATION VARCHAR(100) COMMENT '操作类型',
    RESOURCE VARCHAR(255) COMMENT '操作资源',
    METHOD VARCHAR(10) COMMENT '请求方法',
    URL VARCHAR(500) COMMENT '请求URL',
    IP_ADDRESS VARCHAR(50),
    REQUEST_PARAMS TEXT,
    RESPONSE_RESULT TEXT,
    STATUS INTEGER COMMENT '1:成功 0:失败',
    ERROR_MESSAGE TEXT,
    EXECUTION_TIME INTEGER COMMENT '执行时间(ms)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 插入默认角色
INSERT OR IGNORE INTO ROLES (ROLE_NAME, ROLE_CODE, DESCRIPTION) VALUES
('超级管理员', 'SUPER_ADMIN', '系统超级管理员，拥有所有权限'),
('管理员', 'ADMIN', '系统管理员，拥有大部分管理权限'),
('普通用户', 'USER', '普通用户，基础操作权限'),
('访客', 'GUEST', '访客用户，只读权限');

-- 插入默认权限
INSERT OR IGNORE INTO PERMISSIONS (PERMISSION_NAME, PERMISSION_CODE, RESOURCE_TYPE, RESOURCE_PATH, DESCRIPTION, PARENT_ID) VALUES
('系统管理', 'SYSTEM', 'menu', '/system', '系统管理模块', NULL),
('用户管理', 'SYSTEM:USER', 'menu', '/system/user', '用户管理', 1),
('用户查看', 'SYSTEM:USER:VIEW', 'button', '', '查看用户列表', 2),
('用户新增', 'SYSTEM:USER:CREATE', 'button', '', '新增用户', 2),
('用户编辑', 'SYSTEM:USER:EDIT', 'button', '', '编辑用户', 2),
('用户删除', 'SYSTEM:USER:DELETE', 'button', '', '删除用户', 2),
('角色管理', 'SYSTEM:ROLE', 'menu', '/system/role', '角色管理', 1),
('权限管理', 'SYSTEM:PERMISSION', 'menu', '/system/permission', '权限管理', 1),
('流程图管理', 'FLOWCHART', 'menu', '/flowchart', '流程图管理', NULL),
('流程图查看', 'FLOWCHART:VIEW', 'api', '/flowchart/list', '查看流程图', 9),
('流程图创建', 'FLOWCHART:CREATE', 'api', '/flowchart/create', '创建流程图', 9),
('流程图编辑', 'FLOWCHART:EDIT', 'api', '/flowchart/update', '编辑流程图', 9),
('流程图删除', 'FLOWCHART:DELETE', 'api', '/flowchart/delete', '删除流程图', 9),
('项目管理', 'PROJECT', 'menu', '/project', '项目管理', NULL),
('报文管理', 'PACKET', 'menu', '/packet', '报文管理', NULL);

-- 为超级管理员角色分配所有权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM PERMISSIONS;

-- 为管理员角色分配除系统管理外的权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE NOT LIKE 'SYSTEM:%' OR PERMISSION_CODE IN ('SYSTEM:USER:VIEW', 'SYSTEM:ROLE:VIEW');

-- 为普通用户角色分配基础权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE IN (
    'FLOWCHART:VIEW', 'PROJECT:VIEW', 'PACKET:VIEW'
);

-- 插入默认超级管理员账户 (密码: admin123)
INSERT OR IGNORE INTO USERS (USER_NAME, PASSWORD, REAL_NAME, EMAIL, ROLE_ID)
VALUES ('admin', '$2b$10$rW8FVFlOJ8QzjWFxnfZC0OGnZjf4iL3VjV6RRyc5H/oHjvjeZ9sLy', '系统管理员', 'admin@example.com', 1);

-- 7. 项目管理表
CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PROJECT_NAME VARCHAR(255) NOT NULL COMMENT '项目名称',
    DESCRIPTION TEXT COMMENT '项目描述',
    STATUS VARCHAR(50) NOT NULL COMMENT '状态：待立项、进行中、已暂停、已完成、已取消',
    MANAGER_ID BIGINT NOT NULL COMMENT '项目负责人用户ID',
    DEPARTMENT_ID BIGINT COMMENT '所属部门ID',
    START_DATE TIMESTAMP COMMENT '开始日期',
    END_DATE TIMESTAMP COMMENT '结束日期',
    BUDGET DECIMAL(15, 2) COMMENT '项目预算',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 项目团队表
CREATE TABLE IF NOT EXISTS PROJECT_TEAMS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PROJECT_ID BIGINT NOT NULL COMMENT '项目ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    ROLE VARCHAR(50) NOT NULL COMMENT '角色：项目经理、开发工程师、测试工程师、UI设计师、产品经理',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-正常 0-已移除',
    JOIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. 需求管理表
CREATE TABLE IF NOT EXISTS REQUIREMENTS (
    REQUIREMENT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_NAME VARCHAR(255) NOT NULL COMMENT '需求名称',
    REQUIREMENT_TYPE VARCHAR(50) NOT NULL COMMENT '需求类型：业务需求、技术需求、产品需求',
    DESCRIPTION TEXT COMMENT '需求描述',
    PRIORITY VARCHAR(10) NOT NULL COMMENT '优先级：P0, P1, P2, P3',
    STATUS VARCHAR(50) NOT NULL COMMENT '状态：待设计、待产品评审、待技术评审、开发中、测试中、已上线、已结束',
    CURRENT_ASSIGNEE_ID BIGINT COMMENT '当前负责人用户ID',
    REPORTER_ID BIGINT NOT NULL COMMENT '提出人用户ID',
    PROJECT_ID BIGINT COMMENT '所属项目ID',
    PLANNED_VERSION VARCHAR(50) COMMENT '规划版本',
    ACTUAL_VERSION VARCHAR(50) COMMENT '实际上线版本',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. 任务管理表
CREATE TABLE IF NOT EXISTS TASKS (
    TASK_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    TASK_NAME VARCHAR(255) NOT NULL COMMENT '任务名称',
    DESCRIPTION TEXT COMMENT '任务描述',
    PRIORITY VARCHAR(10) NOT NULL COMMENT '优先级：P0, P1, P2, P3',
    STATUS VARCHAR(50) NOT NULL COMMENT '状态：未开始、进行中、已完成、已取消',
    ASSIGNEE_ID BIGINT COMMENT '负责人用户ID',
    REPORTER_ID BIGINT NOT NULL COMMENT '创建人用户ID',
    REQUIREMENT_ID BIGINT COMMENT '关联需求ID',
    PROJECT_ID BIGINT COMMENT '所属项目ID',
    ESTIMATED_HOURS DECIMAL(10, 2) COMMENT '预估工时(小时)',
    ACTUAL_HOURS DECIMAL(10, 2) COMMENT '实际工时(小时)',
    START_TIME TIMESTAMP COMMENT '开始时间',
    END_TIME TIMESTAMP COMMENT '结束时间',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 缺陷管理表
CREATE TABLE IF NOT EXISTS DEFECTS (
    DEFECT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    DEFECT_NAME VARCHAR(255) NOT NULL COMMENT '缺陷名称',
    DESCRIPTION TEXT COMMENT '缺陷描述',
    SEVERITY VARCHAR(50) NOT NULL COMMENT '严重程度：致命、严重、一般、轻微',
    STATUS VARCHAR(50) NOT NULL COMMENT '状态：待修复、修复中、已修复、已验证、已关闭',
    ASSIGNEE_ID BIGINT COMMENT '负责人用户ID',
    REPORTER_ID BIGINT NOT NULL COMMENT '报告人用户ID',
    REQUIREMENT_ID BIGINT COMMENT '关联需求ID',
    TASK_ID BIGINT COMMENT '关联任务ID',
    PROJECT_ID BIGINT COMMENT '所属项目ID',
    REPRODUCE_STEPS TEXT COMMENT '复现步骤',
    FIX_VERSION VARCHAR(50) COMMENT '修复版本',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. 流程管理表
CREATE TABLE IF NOT EXISTS WORKFLOWS (
    WORKFLOW_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    WORKFLOW_NAME VARCHAR(255) NOT NULL COMMENT '流程名称',
    DESCRIPTION TEXT COMMENT '流程描述',
    WORKFLOW_TYPE VARCHAR(50) NOT NULL COMMENT '流程类型：需求流程、任务流程、缺陷流程、项目流程',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. 流程节点表
CREATE TABLE IF NOT EXISTS WORKFLOW_NODES (
    NODE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    WORKFLOW_ID BIGINT NOT NULL COMMENT '流程ID',
    NODE_NAME VARCHAR(255) NOT NULL COMMENT '节点名称',
    NODE_TYPE VARCHAR(50) NOT NULL COMMENT '节点类型：开始节点、审批节点、执行节点、结束节点',
    NODE_ORDER INTEGER NOT NULL COMMENT '节点顺序',
    ASSIGNEE_TYPE VARCHAR(50) COMMENT '负责人类型：固定用户、角色、部门',
    ASSIGNEE_ID BIGINT COMMENT '负责人ID',
    DURATION_LIMIT INTEGER COMMENT '处理时限(小时)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 14. 流程实例表
CREATE TABLE IF NOT EXISTS WORKFLOW_INSTANCES (
    INSTANCE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    WORKFLOW_ID BIGINT NOT NULL COMMENT '流程ID',
    BUSINESS_TYPE VARCHAR(50) NOT NULL COMMENT '业务类型：需求、任务、缺陷、项目',
    BUSINESS_ID BIGINT NOT NULL COMMENT '业务ID',
    CURRENT_NODE_ID BIGINT COMMENT '当前节点ID',
    STATUS VARCHAR(50) NOT NULL COMMENT '状态：运行中、已完成、已取消',
    CREATE_USER_ID BIGINT NOT NULL COMMENT '创建人用户ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 15. 流程执行记录表
CREATE TABLE IF NOT EXISTS WORKFLOW_EXECUTIONS (
    EXECUTION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    INSTANCE_ID BIGINT NOT NULL COMMENT '流程实例ID',
    NODE_ID BIGINT NOT NULL COMMENT '节点ID',
    EXECUTOR_ID BIGINT NOT NULL COMMENT '执行人用户ID',
    ACTION VARCHAR(50) NOT NULL COMMENT '操作：通过、驳回、转发',
    COMMENT TEXT COMMENT '审批意见',
    START_TIME TIMESTAMP NOT NULL COMMENT '开始时间',
    END_TIME TIMESTAMP COMMENT '结束时间',
    DURATION INTEGER COMMENT '处理时长(分钟)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 16. 标签管理表
CREATE TABLE IF NOT EXISTS TAGS (
    TAG_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    TAG_NAME VARCHAR(50) NOT NULL UNIQUE COMMENT '标签名称',
    TAG_COLOR VARCHAR(20) COMMENT '标签颜色',
    DESCRIPTION VARCHAR(255) COMMENT '标签描述',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 17. 需求标签关联表
CREATE TABLE IF NOT EXISTS REQUIREMENT_TAGS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_ID BIGINT NOT NULL COMMENT '需求ID',
    TAG_ID BIGINT NOT NULL COMMENT '标签ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 18. 评论管理表
CREATE TABLE IF NOT EXISTS COMMENTS (
    COMMENT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    BUSINESS_TYPE VARCHAR(50) NOT NULL COMMENT '业务类型：需求、任务、缺陷',
    BUSINESS_ID BIGINT NOT NULL COMMENT '业务ID',
    USER_ID BIGINT NOT NULL COMMENT '评论人用户ID',
    CONTENT TEXT NOT NULL COMMENT '评论内容',
    PARENT_COMMENT_ID BIGINT COMMENT '父评论ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 19. 操作记录表
CREATE TABLE IF NOT EXISTS OPERATION_RECORDS (
    RECORD_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    BUSINESS_TYPE VARCHAR(50) NOT NULL COMMENT '业务类型：需求、任务、缺陷',
    BUSINESS_ID BIGINT NOT NULL COMMENT '业务ID',
    USER_ID BIGINT NOT NULL COMMENT '操作人用户ID',
    OPERATION_TYPE VARCHAR(50) NOT NULL COMMENT '操作类型：创建、更新、删除、状态变更',
    OPERATION_DETAIL TEXT COMMENT '操作详情',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 20. 通知管理表
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    NOTIFICATION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT NOT NULL COMMENT '接收用户ID',
    TITLE VARCHAR(255) NOT NULL COMMENT '通知标题',
    CONTENT TEXT COMMENT '通知内容',
    TYPE VARCHAR(50) NOT NULL COMMENT '通知类型：系统通知、业务通知、提醒',
    STATUS INTEGER DEFAULT 0 COMMENT '阅读状态：0-未读 1-已读',
    BUSINESS_TYPE VARCHAR(50) COMMENT '关联业务类型',
    BUSINESS_ID BIGINT COMMENT '关联业务ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入项目管理相关权限
INSERT OR IGNORE INTO PERMISSIONS (PERMISSION_NAME, PERMISSION_CODE, RESOURCE_TYPE, RESOURCE_PATH, DESCRIPTION, PARENT_ID) VALUES
('需求管理', 'REQUIREMENT', 'menu', '/requirement', '需求管理模块', NULL),
('需求查看', 'REQUIREMENT:VIEW', 'api', '/api/requirements/query', '查看需求列表', 14),
('需求创建', 'REQUIREMENT:CREATE', 'api', '/api/requirements/create', '创建需求', 14),
('需求编辑', 'REQUIREMENT:EDIT', 'api', '/api/requirements/update', '编辑需求', 14),
('需求删除', 'REQUIREMENT:DELETE', 'api', '/api/requirements/delete', '删除需求', 14),
('任务管理', 'TASK', 'menu', '/task', '任务管理模块', NULL),
('任务查看', 'TASK:VIEW', 'api', '/api/tasks/query', '查看任务列表', 19),
('任务创建', 'TASK:CREATE', 'api', '/api/tasks/create', '创建任务', 19),
('任务编辑', 'TASK:EDIT', 'api', '/api/tasks/update', '编辑任务', 19),
('任务删除', 'TASK:DELETE', 'api', '/api/tasks/delete', '删除任务', 19),
('缺陷管理', 'DEFECT', 'menu', '/defect', '缺陷管理模块', NULL),
('缺陷查看', 'DEFECT:VIEW', 'api', '/api/defects/query', '查看缺陷列表', 24),
('缺陷创建', 'DEFECT:CREATE', 'api', '/api/defects/create', '创建缺陷', 24),
('缺陷编辑', 'DEFECT:EDIT', 'api', '/api/defects/update', '编辑缺陷', 24),
('缺陷删除', 'DEFECT:DELETE', 'api', '/api/defects/delete', '删除缺陷', 24),
('流程管理', 'WORKFLOW', 'menu', '/workflow', '流程管理模块', NULL),
('流程查看', 'WORKFLOW:VIEW', 'api', '/api/workflows/query', '查看流程列表', 29),
('流程创建', 'WORKFLOW:CREATE', 'api', '/api/workflows/create', '创建流程', 29),
('流程编辑', 'WORKFLOW:EDIT', 'api', '/api/workflows/update', '编辑流程', 29),
('流程删除', 'WORKFLOW:DELETE', 'api', '/api/workflows/delete', '删除流程', 29);

-- 为超级管理员分配新增的项目管理权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE LIKE 'REQUIREMENT:%' OR PERMISSION_CODE LIKE 'TASK:%' OR PERMISSION_CODE LIKE 'DEFECT:%' OR PERMISSION_CODE LIKE 'WORKFLOW:%';

-- 为管理员分配项目管理权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM PERMISSIONS WHERE (PERMISSION_CODE LIKE 'REQUIREMENT:%' OR PERMISSION_CODE LIKE 'TASK:%' OR PERMISSION_CODE LIKE 'DEFECT:%' OR PERMISSION_CODE LIKE 'WORKFLOW:%');

-- 为普通用户分配项目管理查看权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE IN (
    'REQUIREMENT:VIEW', 'TASK:VIEW', 'DEFECT:VIEW', 'WORKFLOW:VIEW'
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_users_username ON USERS(USER_NAME);
CREATE INDEX IF NOT EXISTS idx_users_email ON USERS(EMAIL);
CREATE INDEX IF NOT EXISTS idx_users_status ON USERS(STATUS);
CREATE INDEX IF NOT EXISTS idx_user_sessions_userid ON USER_SESSIONS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON USER_SESSIONS(TOKEN);
CREATE INDEX IF NOT EXISTS idx_operation_logs_userid ON OPERATION_LOGS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_operation_logs_createtime ON OPERATION_LOGS(CREATE_TIME);
CREATE INDEX IF NOT EXISTS idx_projects_status ON PROJECTS(STATUS);
CREATE INDEX IF NOT EXISTS idx_projects_manager ON PROJECTS(MANAGER_ID);
CREATE INDEX IF NOT EXISTS idx_project_teams_project ON PROJECT_TEAMS(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_project_teams_user ON PROJECT_TEAMS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_requirements_status ON REQUIREMENTS(STATUS);
CREATE INDEX IF NOT EXISTS idx_requirements_priority ON REQUIREMENTS(PRIORITY);
CREATE INDEX IF NOT EXISTS idx_requirements_project ON REQUIREMENTS(PROJECT_ID);
CREATE INDEX IF NOT EXISTS idx_requirements_current_assignee ON REQUIREMENTS(CURRENT_ASSIGNEE_ID);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON TASKS(STATUS);
CREATE INDEX IF NOT EXISTS idx_tasks_priority ON TASKS(PRIORITY);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON TASKS(ASSIGNEE_ID);
CREATE INDEX IF NOT EXISTS idx_tasks_requirement ON TASKS(REQUIREMENT_ID);
CREATE INDEX IF NOT EXISTS idx_defects_status ON DEFECTS(STATUS);
CREATE INDEX IF NOT EXISTS idx_defects_severity ON DEFECTS(SEVERITY);
CREATE INDEX IF NOT EXISTS idx_defects_assignee ON DEFECTS(ASSIGNEE_ID);
CREATE INDEX IF NOT EXISTS idx_workflows_type ON WORKFLOWS(WORKFLOW_TYPE);
CREATE INDEX IF NOT EXISTS idx_workflow_nodes_workflow ON WORKFLOW_NODES(WORKFLOW_ID);
CREATE INDEX IF NOT EXISTS idx_workflow_nodes_order ON WORKFLOW_NODES(NODE_ORDER);
CREATE INDEX IF NOT EXISTS idx_workflow_instances_business ON WORKFLOW_INSTANCES(BUSINESS_TYPE, BUSINESS_ID);
CREATE INDEX IF NOT EXISTS idx_workflow_instances_status ON WORKFLOW_INSTANCES(STATUS);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_instance ON WORKFLOW_EXECUTIONS(INSTANCE_ID);
CREATE INDEX IF NOT EXISTS idx_workflow_executions_node ON WORKFLOW_EXECUTIONS(NODE_ID);
CREATE INDEX IF NOT EXISTS idx_tags_name ON TAGS(TAG_NAME);
CREATE INDEX IF NOT EXISTS idx_requirement_tags_requirement ON REQUIREMENT_TAGS(REQUIREMENT_ID);
CREATE INDEX IF NOT EXISTS idx_requirement_tags_tag ON REQUIREMENT_TAGS(TAG_ID);
CREATE INDEX IF NOT EXISTS idx_comments_business ON COMMENTS(BUSINESS_TYPE, BUSINESS_ID);
CREATE INDEX IF NOT EXISTS idx_comments_user ON COMMENTS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_operation_records_business ON OPERATION_RECORDS(BUSINESS_TYPE, BUSINESS_ID);
CREATE INDEX IF NOT EXISTS idx_operation_records_user ON OPERATION_RECORDS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_operation_records_type ON OPERATION_RECORDS(OPERATION_TYPE);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON NOTIFICATIONS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON NOTIFICATIONS(STATUS);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON NOTIFICATIONS(TYPE);