-- 用户认证与权限管理相关表结构
-- 创建时间: 2025-11-24

-- 1. 用户表 (扩展现有USERS表)
-- 如果USERS表不存在则创建
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    REAL_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    AVATAR VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    ROLE_ID BIGINT,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN_TIME TIMESTAMP,
    LAST_LOGIN_IP VARCHAR(50)
);

-- 2. 角色表
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROLE_CODE VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 权限表
CREATE TABLE IF NOT EXISTS PERMISSIONS (
    PERMISSION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    PERMISSION_CODE VARCHAR(100) UNIQUE NOT NULL,
    RESOURCE_TYPE VARCHAR(50) COMMENT '资源类型: menu, button, api',
    RESOURCE_PATH VARCHAR(255) COMMENT '资源路径',
    DESCRIPTION VARCHAR(255),
    PARENT_ID BIGINT,
    SORT_ORDER INTEGER DEFAULT 0,
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 角色权限关联表
CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. 用户会话表 (用于JWT黑名单和会话管理)
CREATE TABLE IF NOT EXISTS USER_SESSIONS (
    SESSION_ID VARCHAR(255) PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(500) NOT NULL,
    REFRESH_TOKEN VARCHAR(500),
    EXPIRES_AT TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(50),
    USER_AGENT VARCHAR(500),
    STATUS INTEGER DEFAULT 1 COMMENT '1:有效 0:已注销',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. 操作日志表
CREATE TABLE IF NOT EXISTS OPERATION_LOGS (
    LOG_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT,
    USER_NAME VARCHAR(50),
    OPERATION VARCHAR(100) COMMENT '操作类型',
    RESOURCE VARCHAR(255) COMMENT '操作资源',
    METHOD VARCHAR(10) COMMENT '请求方法',
    URL VARCHAR(500) COMMENT '请求URL',
    IP_ADDRESS VARCHAR(50),
    REQUEST_PARAMS TEXT,
    RESPONSE_RESULT TEXT,
    STATUS INTEGER COMMENT '1:成功 0:失败',
    ERROR_MESSAGE TEXT,
    EXECUTION_TIME INTEGER COMMENT '执行时间(ms)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入默认角色
INSERT OR IGNORE INTO ROLES (ROLE_NAME, ROLE_CODE, DESCRIPTION) VALUES
('超级管理员', 'SUPER_ADMIN', '系统超级管理员，拥有所有权限'),
('管理员', 'ADMIN', '系统管理员，拥有大部分管理权限'),
('普通用户', 'USER', '普通用户，基础操作权限'),
('访客', 'GUEST', '访客用户，只读权限');

-- 插入默认权限
INSERT OR IGNORE INTO PERMISSIONS (PERMISSION_NAME, PERMISSION_CODE, RESOURCE_TYPE, RESOURCE_PATH, DESCRIPTION, PARENT_ID) VALUES
('系统管理', 'SYSTEM', 'menu', '/system', '系统管理模块', NULL),
('用户管理', 'SYSTEM:USER', 'menu', '/system/user', '用户管理', 1),
('用户查看', 'SYSTEM:USER:VIEW', 'button', '', '查看用户列表', 2),
('用户新增', 'SYSTEM:USER:CREATE', 'button', '', '新增用户', 2),
('用户编辑', 'SYSTEM:USER:EDIT', 'button', '', '编辑用户', 2),
('用户删除', 'SYSTEM:USER:DELETE', 'button', '', '删除用户', 2),
('角色管理', 'SYSTEM:ROLE', 'menu', '/system/role', '角色管理', 1),
('权限管理', 'SYSTEM:PERMISSION', 'menu', '/system/permission', '权限管理', 1),
('流程图管理', 'FLOWCHART', 'menu', '/flowchart', '流程图管理', NULL),
('流程图查看', 'FLOWCHART:VIEW', 'api', '/flowchart/list', '查看流程图', 9),
('流程图创建', 'FLOWCHART:CREATE', 'api', '/flowchart/create', '创建流程图', 9),
('流程图编辑', 'FLOWCHART:EDIT', 'api', '/flowchart/update', '编辑流程图', 9),
('流程图删除', 'FLOWCHART:DELETE', 'api', '/flowchart/delete', '删除流程图', 9),
('项目管理', 'PROJECT', 'menu', '/project', '项目管理', NULL),
('报文管理', 'PACKET', 'menu', '/packet', '报文管理', NULL);

-- 为超级管理员角色分配所有权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM PERMISSIONS;

-- 为管理员角色分配除系统管理外的权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE NOT LIKE 'SYSTEM:%' OR PERMISSION_CODE IN ('SYSTEM:USER:VIEW', 'SYSTEM:ROLE:VIEW');

-- 为普通用户角色分配基础权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE IN (
    'FLOWCHART:VIEW', 'PROJECT:VIEW', 'PACKET:VIEW'
);

-- 插入默认超级管理员账户 (密码: admin123)
INSERT OR IGNORE INTO USERS (USER_NAME, PASSWORD, REAL_NAME, EMAIL, ROLE_ID)
VALUES ('admin', '$2b$10$rW8FVFlOJ8QzjWFxnfZC0OGnZjf4iL3VjV6RRyc5H/oHjvjeZ9sLy', '系统管理员', 'admin@example.com', 1);

-- 插入需求类型初始数据
INSERT OR IGNORE INTO REQUIREMENT_TYPES (TYPE_NAME, DESCRIPTION, SORT_ORDER) VALUES
('业务需求', '与业务流程相关的需求', 1),
('技术需求', '与技术实现相关的需求', 2),
('产品需求', '与产品功能相关的需求', 3);

-- 插入需求状态初始数据
INSERT OR IGNORE INTO REQUIREMENT_STATUSES (STATUS_NAME, DESCRIPTION, SORT_ORDER) VALUES
('待设计', '需求已提出，待进行设计', 1),
('待产品评审', '设计完成，待产品评审', 2),
('待技术评审', '产品评审通过，待技术评审', 3),
('开发中', '技术评审通过，正在开发', 4),
('测试中', '开发完成，正在测试', 5),
('已上线', '测试通过，已上线', 6),
('已结束', '需求已完成', 7);

-- 插入需求任务状态初始数据
INSERT OR IGNORE INTO REQUIREMENT_TASK_STATUSES (STATUS_NAME, DESCRIPTION, SORT_ORDER) VALUES
('未开始', '任务尚未开始', 1),
('进行中', '任务正在执行', 2),
('已完成', '任务已完成', 3),
('已取消', '任务已取消', 4);

-- 插入流程节点类型初始数据
INSERT OR IGNORE INTO PROCESS_NODE_TYPES (NODE_TYPE_NAME, DESCRIPTION, SORT_ORDER) VALUES
('需求评审', '需求评审节点', 1),
('技术设计', '技术设计节点', 2),
('开发', '开发节点', 3),
('测试', '测试节点', 4),
('上线', '上线节点', 5);

-- 7. 项目管理表
CREATE TABLE IF NOT EXISTS PROJECTS (
    PROJECT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(255) NOT NULL COMMENT '项目名称',
    DESCRIPTION TEXT COMMENT '项目描述',
    STATUS INTEGER NOT NULL COMMENT '状态：1-待立项 2-进行中 3-已暂停 4-已完成 5-已取消',
    MANAGER_ID BIGINT NOT NULL COMMENT '项目负责人用户ID',
    DEPARTMENT_ID BIGINT COMMENT '所属部门ID',
    START_DATE TIMESTAMP COMMENT '开始日期',
    END_DATE TIMESTAMP COMMENT '结束日期',
    BUDGET DECIMAL(15, 2) COMMENT '项目预算',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 8. 项目团队表
CREATE TABLE IF NOT EXISTS PROJECT_TEAMS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PROJECT_ID BIGINT NOT NULL COMMENT '所属项目ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    ROLE_ID BIGINT NOT NULL COMMENT '角色ID',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-正常 0-已移除',
    JOIN_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LEAVE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. 需求管理表
CREATE TABLE IF NOT EXISTS REQUIREMENTS (
    REQUIREMENT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(255) NOT NULL COMMENT '需求名称',
    TYPE_ID BIGINT NOT NULL COMMENT '需求类型ID，关联requirement_types表',
    DESCRIPTION TEXT COMMENT '需求描述',
    PRIORITY INTEGER NOT NULL COMMENT '优先级：1-P0 2-P1 3-P2 4-P3',
    STATUS_ID BIGINT NOT NULL COMMENT '需求状态ID，关联requirement_statuses表',
    CURRENT_ASSIGNEE_ID BIGINT COMMENT '当前负责人用户ID',
    REPORTER_ID BIGINT NOT NULL COMMENT '提出人用户ID',
    PROJECT_ID BIGINT COMMENT '所属项目ID',
    PLANNED_VERSION VARCHAR(50) COMMENT '规划版本',
    ACTUAL_VERSION VARCHAR(50) COMMENT '实际上线版本',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. 任务管理表
CREATE TABLE IF NOT EXISTS TASKS (
    TASK_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NAME VARCHAR(255) NOT NULL COMMENT '任务名称',
    DESCRIPTION TEXT COMMENT '任务描述',
    PRIORITY INTEGER NOT NULL COMMENT '优先级：1-P0 2-P1 3-P2 4-P3',
    TASK_STATUS_ID BIGINT NOT NULL COMMENT '任务状态ID，关联requirement_task_statuses表',
    ASSIGNEE_ID BIGINT COMMENT '负责人用户ID',
    REPORTER_ID BIGINT NOT NULL COMMENT '创建人用户ID',
    REQUIREMENT_ID BIGINT COMMENT '关联需求ID',
    REVIEW_ID BIGINT COMMENT '关联评审ID',
    REQUIREMENT_NODE_ID BIGINT COMMENT '需求管理流程节点ID，关联requirement_process_nodes表',
    REVIEW_NODE_ID BIGINT COMMENT '评审管理流程节点ID，关联review_process_nodes表',
    ESTIMATED_HOURS DECIMAL(10, 2) COMMENT '预估工时(小时)',
    ACTUAL_HOURS DECIMAL(10, 2) COMMENT '实际工时(小时)',
    START_TIME TIMESTAMP COMMENT '开始时间',
    END_TIME TIMESTAMP COMMENT '结束时间',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 评审管理表
CREATE TABLE IF NOT EXISTS REVIEWS (
    REVIEW_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PROJECT_ID BIGINT NOT NULL COMMENT '所属项目ID',
    NAME VARCHAR(255) NOT NULL COMMENT '评审名称',
    DESCRIPTION TEXT COMMENT '评审描述',
    REVIEW_TYPE INTEGER NOT NULL DEFAULT 1 COMMENT '评审类型：1-技术评审 2-业务评审 3-产品评审',
    STATUS INTEGER NOT NULL DEFAULT 1 COMMENT '评审状态：1-待开始 2-进行中 3-已完成 4-已取消',
    REPORTER_ID BIGINT NOT NULL COMMENT '评审发起人用户ID',
    REVIEWER_ID BIGINT COMMENT '评审负责人用户ID',
    START_TIME TIMESTAMP COMMENT '开始时间',
    END_TIME TIMESTAMP COMMENT '结束时间',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. 需求管理流程节点表
CREATE TABLE IF NOT EXISTS REQUIREMENT_PROCESS_NODES (
    NODE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_ID BIGINT NOT NULL COMMENT '关联需求ID',
    NAME VARCHAR(255) NOT NULL COMMENT '节点名称',
    NODE_TYPE_ID BIGINT NOT NULL COMMENT '流程节点类型ID，关联process_node_types表',
    PARENT_NODE_ID BIGINT COMMENT '父节点ID，支持树形结构',
    NODE_ORDER INTEGER NOT NULL COMMENT '节点顺序',
    ASSIGNEE_TYPE INTEGER COMMENT '负责人类型：1-固定用户 2-角色 3-部门',
    ASSIGNEE_ID BIGINT COMMENT '负责人ID',
    DURATION_LIMIT INTEGER COMMENT '处理时限(小时)',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. 需求管理流程节点关系表
CREATE TABLE IF NOT EXISTS REQUIREMENT_PROCESS_NODE_RELATIONS (
    RELATION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_ID BIGINT NOT NULL COMMENT '关联需求ID',
    SOURCE_NODE_ID BIGINT NOT NULL COMMENT '源节点ID',
    TARGET_NODE_ID BIGINT NOT NULL COMMENT '目标节点ID',
    RELATION_TYPE INTEGER DEFAULT 1 COMMENT '关系类型：1-顺序 2-并行 3-条件',
    CONDITION TEXT COMMENT '条件表达式（如：状态=通过）',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 14. 需求管理流程节点用户关联表
CREATE TABLE IF NOT EXISTS REQUIREMENT_PROCESS_NODE_USERS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NODE_ID BIGINT NOT NULL COMMENT '流程节点ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    ROLE_TYPE INTEGER DEFAULT 1 COMMENT '用户角色类型：1-负责人 2-参与者 3-观察者',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-正常 0-已移除',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 15. 评审管理流程节点表
CREATE TABLE IF NOT EXISTS REVIEW_PROCESS_NODES (
    NODE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REVIEW_ID BIGINT NOT NULL COMMENT '关联评审ID',
    NAME VARCHAR(255) NOT NULL COMMENT '节点名称',
    NODE_TYPE_ID BIGINT NOT NULL COMMENT '流程节点类型ID，关联process_node_types表',
    PARENT_NODE_ID BIGINT COMMENT '父节点ID，支持树形结构',
    NODE_ORDER INTEGER NOT NULL COMMENT '节点顺序',
    ASSIGNEE_TYPE INTEGER COMMENT '负责人类型：1-固定用户 2-角色 3-部门',
    ASSIGNEE_ID BIGINT COMMENT '负责人ID',
    DURATION_LIMIT INTEGER COMMENT '处理时限(小时)',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 16. 评审管理流程节点关系表
CREATE TABLE IF NOT EXISTS REVIEW_PROCESS_NODE_RELATIONS (
    RELATION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REVIEW_ID BIGINT NOT NULL COMMENT '关联评审ID',
    SOURCE_NODE_ID BIGINT NOT NULL COMMENT '源节点ID',
    TARGET_NODE_ID BIGINT NOT NULL COMMENT '目标节点ID',
    RELATION_TYPE INTEGER DEFAULT 1 COMMENT '关系类型：1-顺序 2-并行 3-条件',
    CONDITION TEXT COMMENT '条件表达式（如：状态=通过）',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 17. 评审管理流程节点用户关联表
CREATE TABLE IF NOT EXISTS REVIEW_PROCESS_NODE_USERS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NODE_ID BIGINT NOT NULL COMMENT '流程节点ID',
    USER_ID BIGINT NOT NULL COMMENT '用户ID',
    ROLE_TYPE INTEGER DEFAULT 1 COMMENT '用户角色类型：1-负责人 2-参与者 3-观察者',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-正常 0-已移除',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 11. 流程节点类型表
CREATE TABLE IF NOT EXISTS PROCESS_NODE_TYPES (
    NODE_TYPE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    NODE_TYPE_NAME VARCHAR(255) NOT NULL COMMENT '流程节点类型名称：需求评审、技术设计、开发、测试、上线',
    DESCRIPTION TEXT COMMENT '流程节点类型描述',
    SORT_ORDER INTEGER DEFAULT 0 COMMENT '排序顺序',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. 需求类型表
CREATE TABLE IF NOT EXISTS REQUIREMENT_TYPES (
    TYPE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    TYPE_NAME VARCHAR(255) NOT NULL COMMENT '需求类型名称：业务需求、技术需求、产品需求',
    DESCRIPTION TEXT COMMENT '需求类型描述',
    SORT_ORDER INTEGER DEFAULT 0 COMMENT '排序顺序',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. 需求状态表
CREATE TABLE IF NOT EXISTS REQUIREMENT_STATUSES (
    STATUS_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    STATUS_NAME VARCHAR(255) NOT NULL COMMENT '需求状态名称：待设计、待产品评审、待技术评审、开发中、测试中、已上线、已结束',
    DESCRIPTION TEXT COMMENT '需求状态描述',
    SORT_ORDER INTEGER DEFAULT 0 COMMENT '排序顺序',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 14. 需求任务状态表
CREATE TABLE IF NOT EXISTS REQUIREMENT_TASK_STATUSES (
    TASK_STATUS_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    STATUS_NAME VARCHAR(255) NOT NULL COMMENT '任务状态名称：未开始、进行中、已完成、已取消',
    DESCRIPTION TEXT COMMENT '任务状态描述',
    SORT_ORDER INTEGER DEFAULT 0 COMMENT '排序顺序',
    STATUS INTEGER DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 18. 评论管理表
CREATE TABLE IF NOT EXISTS COMMENTS (
    COMMENT_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    BUSINESS_TYPE INTEGER NOT NULL COMMENT '业务类型：1-需求 2-任务',
    BUSINESS_ID BIGINT NOT NULL COMMENT '业务ID',
    USER_ID BIGINT NOT NULL COMMENT '评论人用户ID',
    CONTENT TEXT NOT NULL COMMENT '评论内容',
    PARENT_COMMENT_ID BIGINT COMMENT '父评论ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 19. 操作记录表
CREATE TABLE IF NOT EXISTS OPERATION_RECORDS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    BUSINESS_TYPE INTEGER NOT NULL COMMENT '业务类型：1-需求 2-任务 3-项目 4-流程节点 5-评审维度',
    BUSINESS_ID BIGINT NOT NULL COMMENT '关联的业务ID',
    USER_ID BIGINT NOT NULL COMMENT '操作人用户ID',
    OPERATION_TYPE INTEGER NOT NULL COMMENT '操作类型：1-创建 2-更新 3-删除 4-状态变更 5-分配 6-评论 7-审批',
    OPERATION_DETAIL TEXT COMMENT '操作详情（JSON格式，包含变更前和变更后的数据）',
    IP_ADDRESS VARCHAR(50) COMMENT '操作人IP地址',
    USER_AGENT VARCHAR(255) COMMENT '用户代理（浏览器信息）',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 20. 通知管理表
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    NOTIFICATION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT NOT NULL COMMENT '接收用户ID',
    TITLE VARCHAR(255) NOT NULL COMMENT '通知标题',
    CONTENT TEXT COMMENT '通知内容',
    TYPE INTEGER NOT NULL COMMENT '通知类型：1-系统通知 2-业务通知 3-提醒',
    STATUS INTEGER DEFAULT 0 COMMENT '阅读状态：0-未读 1-已读',
    BUSINESS_TYPE INTEGER COMMENT '关联业务类型',
    BUSINESS_ID BIGINT COMMENT '关联业务ID',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- 23. 流程执行记录表
CREATE TABLE IF NOT EXISTS PROCESS_EXECUTIONS (
    EXECUTION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_ID BIGINT NOT NULL COMMENT '关联需求ID',
    NODE_ID BIGINT NOT NULL COMMENT '节点ID',
    EXECUTOR_ID BIGINT COMMENT '执行人用户ID',
    ACTION INTEGER NOT NULL COMMENT '操作：1-通过 2-驳回 3-转发',
    COMMENT TEXT COMMENT '审批意见',
    START_TIME TIMESTAMP NOT NULL COMMENT '开始时间',
    END_TIME TIMESTAMP COMMENT '结束时间',
    DURATION INTEGER COMMENT '处理时长(分钟)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 22. 数据导入导出记录表
CREATE TABLE IF NOT EXISTS DATA_IMPORT_EXPORTS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT NOT NULL COMMENT '操作人用户ID',
    OPERATION_TYPE INTEGER NOT NULL COMMENT '操作类型：1-导入 2-导出',
    DATA_TYPE INTEGER NOT NULL COMMENT '数据类型：1-需求 2-任务 3-项目',
    FILE_NAME VARCHAR(255) COMMENT '文件名',
    FILE_SIZE BIGINT COMMENT '文件大小(字节)',
    STATUS INTEGER NOT NULL COMMENT '状态：1-成功 0-失败',
    ERROR_MESSAGE TEXT COMMENT '错误信息',
    RECORD_COUNT INTEGER COMMENT '处理记录数',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 23. 需求版本管理表
CREATE TABLE IF NOT EXISTS REQUIREMENT_VERSIONS (
    VERSION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    REQUIREMENT_ID BIGINT NOT NULL COMMENT '关联需求ID',
    NAME VARCHAR(255) NOT NULL COMMENT '版本名称',
    DESCRIPTION TEXT COMMENT '版本描述',
    PLANNED_START_TIME TIMESTAMP COMMENT '计划开始时间',
    PLANNED_END_TIME TIMESTAMP COMMENT '计划结束时间',
    ACTUAL_START_TIME TIMESTAMP COMMENT '实际开始时间',
    ACTUAL_END_TIME TIMESTAMP COMMENT '实际结束时间',
    STATUS INTEGER NOT NULL COMMENT '状态：1-规划中 2-进行中 3-已完成 4-已取消',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 24. 评审维度管理表
CREATE TABLE IF NOT EXISTS REVIEW_DIMENSIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PROJECT_ID BIGINT NOT NULL COMMENT '所属项目ID',
    NAME VARCHAR(255) NOT NULL COMMENT '评审维度名称',
    DESCRIPTION TEXT COMMENT '评审维度描述',
    DIMENSION_TYPE INTEGER NOT NULL DEFAULT 1 COMMENT '评审维度类型：1-技术评审 2-业务评审 3-产品评审',
    WEIGHT DECIMAL(5, 2) NOT NULL DEFAULT 1.00 COMMENT '评审维度权重',
    STATUS INTEGER NOT NULL DEFAULT 1 COMMENT '状态：1-启用 0-禁用',
    SORT_ORDER INTEGER NOT NULL DEFAULT 0 COMMENT '排序顺序',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 插入项目管理相关权限
INSERT OR IGNORE INTO PERMISSIONS (PERMISSION_NAME, PERMISSION_CODE, RESOURCE_TYPE, RESOURCE_PATH, DESCRIPTION, PARENT_ID) VALUES
('需求管理', 'REQUIREMENT', 'menu', '/requirement', '需求管理模块', NULL),
('需求查看', 'REQUIREMENT:VIEW', 'api', '/api/requirements/query', '查看需求列表', 14),
('需求创建', 'REQUIREMENT:CREATE', 'api', '/api/requirements/create', '创建需求', 14),
('需求编辑', 'REQUIREMENT:EDIT', 'api', '/api/requirements/update', '编辑需求', 14),
('需求删除', 'REQUIREMENT:DELETE', 'api', '/api/requirements/delete', '删除需求', 14),
('任务管理', 'TASK', 'menu', '/task', '任务管理模块', NULL),
('任务查看', 'TASK:VIEW', 'api', '/api/tasks/query', '查看任务列表', 19),
('任务创建', 'TASK:CREATE', 'api', '/api/tasks/create', '创建任务', 19),
('任务编辑', 'TASK:EDIT', 'api', '/api/tasks/update', '编辑任务', 19),
('任务删除', 'TASK:DELETE', 'api', '/api/tasks/delete', '删除任务', 19),
('评审管理', 'REVIEW', 'menu', '/review', '评审管理模块', NULL),
('评审查看', 'REVIEW:VIEW', 'api', '/api/reviews/query', '查看评审列表', 24),
('评审创建', 'REVIEW:CREATE', 'api', '/api/reviews/create', '创建评审', 24),
('评审编辑', 'REVIEW:EDIT', 'api', '/api/reviews/update', '编辑评审', 24),
('评审删除', 'REVIEW:DELETE', 'api', '/api/reviews/delete', '删除评审', 24),
('数据导入导出', 'DATA_IMPORT_EXPORT', 'menu', '/data-import-export', '数据导入导出模块', NULL),
('数据导入', 'DATA_IMPORT_EXPORT:IMPORT', 'api', '/api/data-import-export/import', '导入数据', 29),
('数据导出', 'DATA_IMPORT_EXPORT:EXPORT', 'api', '/api/data-import-export/export', '导出数据', 29),
('需求版本管理', 'REQUIREMENT_VERSION', 'menu', '/requirement-version', '需求版本管理模块', NULL),
('版本查看', 'REQUIREMENT_VERSION:VIEW', 'api', '/api/requirement-versions/query', '查看版本列表', 32),
('版本创建', 'REQUIREMENT_VERSION:CREATE', 'api', '/api/requirement-versions/create', '创建版本', 32),
('版本编辑', 'REQUIREMENT_VERSION:EDIT', 'api', '/api/requirement-versions/update', '编辑版本', 32),
('版本删除', 'REQUIREMENT_VERSION:DELETE', 'api', '/api/requirement-versions/delete', '删除版本', 32),
('评审维度管理', 'REVIEW_DIMENSION', 'menu', '/review-dimension', '评审维度管理模块', NULL),
('评审维度查看', 'REVIEW_DIMENSION:VIEW', 'api', '/api/review-dimensions/query', '查看评审维度列表', 37),
('评审维度创建', 'REVIEW_DIMENSION:CREATE', 'api', '/api/review-dimensions/create', '创建评审维度', 37),
('评审维度编辑', 'REVIEW_DIMENSION:EDIT', 'api', '/api/review-dimensions/update', '编辑评审维度', 37),
('评审维度删除', 'REVIEW_DIMENSION:DELETE', 'api', '/api/review-dimensions/delete', '删除评审维度', 37);

-- 为超级管理员分配新增的项目管理权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE LIKE 'REQUIREMENT:%' OR PERMISSION_CODE LIKE 'TASK:%' OR PERMISSION_CODE LIKE 'REVIEW:%' OR PERMISSION_CODE LIKE 'DATA_IMPORT_EXPORT:%' OR PERMISSION_CODE LIKE 'REQUIREMENT_VERSION:%' OR PERMISSION_CODE LIKE 'REVIEW_DIMENSION:%';

-- 为管理员分配项目管理权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM PERMISSIONS WHERE (PERMISSION_CODE LIKE 'REQUIREMENT:%' OR PERMISSION_CODE LIKE 'TASK:%' OR PERMISSION_CODE LIKE 'REVIEW:%' OR PERMISSION_CODE LIKE 'DATA_IMPORT_EXPORT:%' OR PERMISSION_CODE LIKE 'REQUIREMENT_VERSION:%' OR PERMISSION_CODE LIKE 'REVIEW_DIMENSION:%');

-- 为普通用户分配项目管理查看权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE IN (
    'REQUIREMENT:VIEW', 'TASK:VIEW', 'REVIEW:VIEW', 'DATA_IMPORT_EXPORT:EXPORT', 'REQUIREMENT_VERSION:VIEW', 'REVIEW_DIMENSION:VIEW'
);

