-- 用户认证与权限管理相关表结构
-- 创建时间: 2025-11-24

-- 1. 用户表 (扩展现有USERS表)
-- 如果USERS表不存在则创建
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    REAL_NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    AVATAR VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    ROLE_ID BIGINT,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN_TIME TIMESTAMP,
    LAST_LOGIN_IP VARCHAR(50)
);

-- 2. 角色表
CREATE TABLE IF NOT EXISTS ROLES (
    ROLE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_NAME VARCHAR(50) UNIQUE NOT NULL,
    ROLE_CODE VARCHAR(50) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(255),
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 权限表
CREATE TABLE IF NOT EXISTS PERMISSIONS (
    PERMISSION_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PERMISSION_NAME VARCHAR(100) NOT NULL,
    PERMISSION_CODE VARCHAR(100) UNIQUE NOT NULL,
    RESOURCE_TYPE VARCHAR(50) COMMENT '资源类型: menu, button, api',
    RESOURCE_PATH VARCHAR(255) COMMENT '资源路径',
    DESCRIPTION VARCHAR(255),
    PARENT_ID BIGINT,
    SORT_ORDER INTEGER DEFAULT 0,
    STATUS INTEGER DEFAULT 1 COMMENT '1:启用 0:禁用',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. 角色权限关联表
CREATE TABLE IF NOT EXISTS ROLE_PERMISSIONS (
    ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(PERMISSION_ID),
    UNIQUE (ROLE_ID, PERMISSION_ID)
);

-- 5. 用户会话表 (用于JWT黑名单和会话管理)
CREATE TABLE IF NOT EXISTS USER_SESSIONS (
    SESSION_ID VARCHAR(255) PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    TOKEN VARCHAR(500) NOT NULL,
    REFRESH_TOKEN VARCHAR(500),
    EXPIRES_AT TIMESTAMP NOT NULL,
    IP_ADDRESS VARCHAR(50),
    USER_AGENT VARCHAR(500),
    STATUS INTEGER DEFAULT 1 COMMENT '1:有效 0:已注销',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 6. 操作日志表
CREATE TABLE IF NOT EXISTS OPERATION_LOGS (
    LOG_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USER_ID BIGINT,
    USER_NAME VARCHAR(50),
    OPERATION VARCHAR(100) COMMENT '操作类型',
    RESOURCE VARCHAR(255) COMMENT '操作资源',
    METHOD VARCHAR(10) COMMENT '请求方法',
    URL VARCHAR(500) COMMENT '请求URL',
    IP_ADDRESS VARCHAR(50),
    REQUEST_PARAMS TEXT,
    RESPONSE_RESULT TEXT,
    STATUS INTEGER COMMENT '1:成功 0:失败',
    ERROR_MESSAGE TEXT,
    EXECUTION_TIME INTEGER COMMENT '执行时间(ms)',
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 插入默认角色
INSERT OR IGNORE INTO ROLES (ROLE_NAME, ROLE_CODE, DESCRIPTION) VALUES
('超级管理员', 'SUPER_ADMIN', '系统超级管理员，拥有所有权限'),
('管理员', 'ADMIN', '系统管理员，拥有大部分管理权限'),
('普通用户', 'USER', '普通用户，基础操作权限'),
('访客', 'GUEST', '访客用户，只读权限');

-- 插入默认权限
INSERT OR IGNORE INTO PERMISSIONS (PERMISSION_NAME, PERMISSION_CODE, RESOURCE_TYPE, RESOURCE_PATH, DESCRIPTION, PARENT_ID) VALUES
('系统管理', 'SYSTEM', 'menu', '/system', '系统管理模块', NULL),
('用户管理', 'SYSTEM:USER', 'menu', '/system/user', '用户管理', 1),
('用户查看', 'SYSTEM:USER:VIEW', 'button', '', '查看用户列表', 2),
('用户新增', 'SYSTEM:USER:CREATE', 'button', '', '新增用户', 2),
('用户编辑', 'SYSTEM:USER:EDIT', 'button', '', '编辑用户', 2),
('用户删除', 'SYSTEM:USER:DELETE', 'button', '', '删除用户', 2),
('角色管理', 'SYSTEM:ROLE', 'menu', '/system/role', '角色管理', 1),
('权限管理', 'SYSTEM:PERMISSION', 'menu', '/system/permission', '权限管理', 1),
('流程图管理', 'FLOWCHART', 'menu', '/flowchart', '流程图管理', NULL),
('流程图查看', 'FLOWCHART:VIEW', 'api', '/flowchart/list', '查看流程图', 9),
('流程图创建', 'FLOWCHART:CREATE', 'api', '/flowchart/create', '创建流程图', 9),
('流程图编辑', 'FLOWCHART:EDIT', 'api', '/flowchart/update', '编辑流程图', 9),
('流程图删除', 'FLOWCHART:DELETE', 'api', '/flowchart/delete', '删除流程图', 9),
('项目管理', 'PROJECT', 'menu', '/project', '项目管理', NULL),
('报文管理', 'PACKET', 'menu', '/packet', '报文管理', NULL);

-- 为超级管理员角色分配所有权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM PERMISSIONS;

-- 为管理员角色分配除系统管理外的权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE NOT LIKE 'SYSTEM:%' OR PERMISSION_CODE IN ('SYSTEM:USER:VIEW', 'SYSTEM:ROLE:VIEW');

-- 为普通用户角色分配基础权限
INSERT OR IGNORE INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM PERMISSIONS WHERE PERMISSION_CODE IN (
    'FLOWCHART:VIEW', 'PROJECT:VIEW', 'PACKET:VIEW'
);

-- 插入默认超级管理员账户 (密码: admin123)
INSERT OR IGNORE INTO USERS (USER_NAME, PASSWORD, REAL_NAME, EMAIL, ROLE_ID)
VALUES ('admin', '$2b$10$rW8FVFlOJ8QzjWFxnfZC0OGnZjf4iL3VjV6RRyc5H/oHjvjeZ9sLy', '系统管理员', 'admin@example.com', 1);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_users_username ON USERS(USER_NAME);
CREATE INDEX IF NOT EXISTS idx_users_email ON USERS(EMAIL);
CREATE INDEX IF NOT EXISTS idx_users_status ON USERS(STATUS);
CREATE INDEX IF NOT EXISTS idx_user_sessions_userid ON USER_SESSIONS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON USER_SESSIONS(TOKEN);
CREATE INDEX IF NOT EXISTS idx_operation_logs_userid ON OPERATION_LOGS(USER_ID);
CREATE INDEX IF NOT EXISTS idx_operation_logs_createtime ON OPERATION_LOGS(CREATE_TIME);